/**
 * Constants
 */
F1000.Globals = {
  ArticleTypes: {
    ANTIBODY_VALIDATION_ARTICLE: 'Antibody Validation Article',
    BOOK_CHAPTER: 'Book Chapter',
    BRIEF_REPORT: 'Brief Report',
    CASE_REPORT: 'Case Report',
    CASE_STUDY: 'Case Study',
    CLINICAL_PRACTICE_ARTICLE: 'Clinical Practice Article',
    COMMENTARY: 'Commentary',
    COMMENTARY_LEGACY: 'Commentary',
    CORRESPONDENCE: 'Correspondence',
    DATA_ARTICLE: 'Data Article',
    DATA_NOTE: 'Data Note',
    EDITORIAL: 'Editorial',
    ESSAY: 'Essay',
    F1000_FACULTY_CRITIQUE: 'F1000 Faculty Critique',
    METHOD_ARTICLE: 'Method Article',
    NEW_EDUCATIONAL_METHODS: 'New Educational Method',
    GENOME_NOTE: 'Genome Note',
    OBSERVATION_ARTICLES: 'Observation Article',
    OPEN_LETTER: 'Open Letter',
    OPINION_ARTICLE: 'Opinion Article',
    POLICY_BRIEF: 'Policy Brief',
    PRACTICAL_TIPS: 'Practical Tips',
    RESEARCH_ARTICLE: 'Research Article',
    RESEARCH_NOTE: 'Research Note',
    RETRACTION: 'Retraction',
    REVIEW: 'Review',
    SHORT_RESEARCH_ARTICLE: 'Short Research Article',
    SINGLE_FIGURE_NOTE: 'Single-Figure Note',
    SOFTWARE_TOOLS: 'Software Tool Article',
    STUDY_PROTOCOL: 'Study Protocol',
    SYSTEMATIC_REVIEW: 'Systematic Review',
    THOUGHT_EXPERIMENT: 'Thought Experiment',
    WEB_TOOLS: 'Web Tool',
    COMMENTARY: 'Commentary'
  },
  CheckLevels: {
    OPEN_RESEARCH_PREPRINT_CHECKS: 'Open Research Preprint Checks',
    VERIFIED_PREPRINT_CHECKS: 'Verified Preprint Checks'
  },
  Classes: {
    ACTIVE: 'is-active',
    CHECKED: 'is-checked',
    CONFIRM_ACTION: 'js-confirm-action',
    CLOSED: 'is-closed',
    DISABLED: 'is-disabled',
    EDIT: 'is-edit',
    HIDDEN: 'is-hidden',
    HIDDEN_IMPORTANT: 'is-hidden-important',
    INDETERMINATE: 'is-indeterminate',
    INVALID: 'is-invalid',
    NEW: 'is-new',
    OPEN: 'is-open',
    PINNED: 'is-pinned',
    SELECTED: 'is-selected'
  },
  Disciplines: {
      HUMANITIES: 'Humanities',
      SCIENCE_TECHNOLOGY_MEDICINE: 'STEM',
      SOCIAL_SCIENCE: 'Social Science'
  },
  KeyCodes: {
    ARROWDOWN: 40,
    ARROWLEFT: 37,
    ARROWRIGHT: 39,
    ARROWUP: 38,
    END: 35,
    HOME: 36,
    PAGEDOWN: 34,
    PAGEUP: 33,
    ASTERISK: 106,
    ENTER: 13,
    ESCAPE: 27,
    SPACE: 32,
    TAB: 9
  },
  Languages: {
    AR: 'Arabic',
    DE: 'German',
    EN: 'English',
    ES: 'Spanish',
    FR: 'French',
    IT: 'Italian',
    JA: 'Japanese'
  },
  LanguageCodes: {
    ARABIC: 'AR',
    ENGLISH: 'EN',
    GERMAN: 'DE',
    FRENCH: 'FR',
    ITALIAN: 'IT',
    JAPANESE: 'JA',
    SPANISH: 'ES'
  },
  MimeTypes: {
    PDF: 'application/pdf',
    WORD: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    XML: 'application/xml',
    ZIP: ['application/zip', 'application/octet-stream', 'application/x-zip-compressed', 'multipart/x-zip']
  },
  Statuses: {
    AUTHOR_DRAFT: 'Author Draft',
    PRESCREENING: 'Pending Pre-Screening',
    PRESCREENING_IN_PROGRESS: 'Pre-screening in Progress',
    PRESCREENING_REJECTED: 'Pre-Screening Rejected',
    PREACCEPTANCE: 'Submitted',
    INITIAL_CHECKS: 'Initial Checks',
    READY_FOR_VERIFIED_PREPRINT_CHECKS: 'Ready for Verified Preprint Checks',
    READY_FOR_OPEN_RESEARCH_CHECKS: 'Ready for Open Research Checks',
    READY_FOR_PREPUB_CHECKS: 'Ready for Content Checks',
    AT_PREPUB_CHECK: 'Prepare to Send to Authors',
    PREPUBLICATION_PEER_REVIEW: 'Pre-Publication Peer Review',
    PREPUB_AUTHORS: 'Revisions with Authors',
    IN_EDITING: 'Pre-Production',
    READY_FOR_ML: 'Sent to Production',
    SENT_TO_MC: 'Sent to Typesetters',
    BACK_FROM_TYPESETTERS: 'Back from Typesetters',
    AUTHOR_PDF_CHECK: 'PDF with Author',
    XML_PDF_REVISIONS: 'Returned to Typesetters',
    FINAL_CHECK_DONE: 'Final Check',
    READY_TO_PUBLISH: 'Ready to Publish',
    PUBLISHED: 'Published',
    PEER_REVIEW_REQUESTED: 'Peer Review Requested',
    CHECKING_VOR_REQUIREMENTS: 'Checking VoR Requirements',
    UNDERGOING_PEER_REVIEW: 'Undergoing Peer Review',
    PASSED_PEER_REVIEW: 'Passed Peer Review',
    NOT_PASSED_PEER_REVIEW: 'Not Passed Peer Review',
    SENT_TO_VERSION_OF_RECORD: 'Sent to Version of Record ',
    COMPLETED: 'Completed',
    RETURN_TO_PUBLISHED: 'Return to Published',
    PLAGIARISM: 'On Hold (Generic)',
    ON_HOLD: 'Escalated to Content Team',
    SUGGEST_ARCHIVE: 'Suggest Archive',
    REJECTED: 'Rejected',
    WITHDRAWN: 'Withdrawn',
    REMOVED: 'Removed',
    RETRACTED: 'Retracted',
    CONCERN: 'On Hold (Escalation)'
  }
};
